### ISSUE TITLE
no get_bowerstatic_url in request

### ISSUE THREAD

**Issue by jjgalvez** [mrijken/pyramid_bowerstatic#1]
no get_bowerstatic_url in request. I did find get_bowerstatic_path in request did you mean for that to be used rather than url?

**Comment by mrijken** [comment]
The path is the url without scheme and servername. If the path is used in a
page on the same scheme and servername, the path will be enough. Or is
there a use case for a get_bowerstatic_url in the request?

2014-12-31 17:31 GMT+01:00 Jose Galvez notifications@github.com:

**Comment by jjgalvez** [comment]
Not sure if there is a use case for it or not, but it's in the docs and would be inline with functions that support normal static resources 

-------- Original Message --------
Subject: Re: [pyramid_bowerstatic] no get_bowerstatic_url in request (#1)

**Comment by mrijken** [comment]
Ah, I have changed the docs, so it is in line with the code.

2015-01-01 23:45 GMT+01:00 Jose Galvez notifications@github.com:
